import React, { useState } from 'react';
import { TrafficStats, Intersection, ZoneMode } from '../types';
import StatCard from '../components/StatCard';
import IntersectionCard from '../components/IntersectionCard';
import { Activity, Car, AlertOctagon, Cpu, CloudRain, Sun, CloudFog, Crown, ShieldOff, FileText, CheckCircle2, Download, X, AlertTriangle } from 'lucide-react';
import { LineChart, Line, ResponsiveContainer, XAxis, YAxis, Tooltip, AreaChart, Area } from 'recharts';

interface DashboardProps {
  stats: TrafficStats;
  intersections: Intersection[];
  onEmergencyToggle: (id: string) => void;
  chartData: any[];
  onZoneAction: (mode: ZoneMode) => void;
  currentZoneMode: ZoneMode;
}

const Dashboard: React.FC<DashboardProps> = ({ stats, intersections, onEmergencyToggle, chartData, onZoneAction, currentZoneMode }) => {
  const [showReportModal, setShowReportModal] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleDownloadReport = () => {
    setDownloading(true);
    setTimeout(() => {
        setDownloading(false);
        setShowReportModal(false);
    }, 1500);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500 relative">
      
      {/* Report Modal */}
      {showReportModal && (
          <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
              <div className="bg-white text-slate-900 rounded-xl w-full max-w-2xl max-h-[80vh] overflow-y-auto shadow-2xl">
                  <div className="p-6 border-b border-slate-200 flex justify-between items-center">
                      <div className="flex items-center gap-2">
                        <FileText className="text-blue-600" size={24} />
                        <h2 className="text-xl font-bold">Monthly Traffic Analysis Report</h2>
                      </div>
                      <button onClick={() => setShowReportModal(false)}><X className="text-slate-400 hover:text-slate-600" /></button>
                  </div>
                  <div className="p-8 space-y-6">
                      <div className="grid grid-cols-2 gap-4">
                          <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
                              <div className="text-xs text-slate-500 uppercase">Reporting Period</div>
                              <div className="font-bold">October 2023</div>
                          </div>
                          <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
                              <div className="text-xs text-slate-500 uppercase">Generated By</div>
                              <div className="font-bold">Admin Officer</div>
                          </div>
                      </div>

                      <table className="w-full text-sm text-left border border-slate-200 rounded-lg overflow-hidden">
                          <thead className="bg-slate-100 text-slate-700 font-bold">
                              <tr>
                                  <th className="p-3">Metric</th>
                                  <th className="p-3">Value</th>
                                  <th className="p-3">Change (YoY)</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr className="border-t border-slate-200">
                                  <td className="p-3">Total Vehicle Flow</td>
                                  <td className="p-3 font-mono">{stats.totalCars.toLocaleString()}</td>
                                  <td className="p-3 text-green-600 font-bold">+12.5%</td>
                              </tr>
                              <tr className="border-t border-slate-200">
                                  <td className="p-3">Avg Wait Time</td>
                                  <td className="p-3 font-mono">42s</td>
                                  <td className="p-3 text-green-600 font-bold">-8.2%</td>
                              </tr>
                              <tr className="border-t border-slate-200">
                                  <td className="p-3">CO2 Emissions</td>
                                  <td className="p-3 font-mono">{stats.avgCo2} tons</td>
                                  <td className="p-3 text-red-600 font-bold">+2.1%</td>
                              </tr>
                          </tbody>
                      </table>

                      <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg text-sm text-yellow-800">
                          <strong>Executive Summary:</strong> Traffic flow has increased significantly in the Downtown sector. AI optimization has successfully mitigated congestion by 15% during peak hours. Recommendation: Upgrade sensor firmware in Sector 7.
                      </div>
                  </div>
                  <div className="p-4 border-t border-slate-200 bg-slate-50 flex justify-end gap-2">
                      <button onClick={() => setShowReportModal(false)} className="px-4 py-2 text-slate-600 hover:bg-slate-200 rounded-lg text-sm font-bold">Close</button>
                      <button onClick={handleDownloadReport} className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-bold flex items-center gap-2">
                          {downloading ? 'Downloading...' : <><Download size={16} /> Download PDF</>}
                      </button>
                  </div>
              </div>
          </div>
      )}

      <div className="flex justify-between items-center">
        <div>
            <h2 className="text-2xl font-bold text-white">System Overview</h2>
            <p className="text-slate-400">Real-time monitoring and AI prediction status.</p>
        </div>
        <div className="flex items-center gap-2">
            <span className="flex h-3 w-3 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500"></span>
            </span>
            <span className="text-sm font-medium text-green-400">AI Active & Monitoring</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Admin Simulation Controls */}
          <div className="bg-slate-800 border border-slate-700 rounded-2xl p-4">
              <div className="flex justify-between items-center mb-4">
                <div>
                    <h4 className="text-white font-bold text-sm">Environmental Simulation</h4>
                    <p className="text-xs text-slate-400">Force system-wide weather adaptation.</p>
                </div>
              </div>
              <div className="flex gap-2">
                 <button className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white transition-colors">
                    <Sun size={14} className="text-yellow-400" /> Clear
                 </button>
                 <button className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white transition-colors">
                    <CloudRain size={14} className="text-blue-400" /> Rain
                 </button>
                 <button className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white transition-colors">
                    <CloudFog size={14} className="text-slate-400" /> Fog
                 </button>
              </div>
          </div>

          {/* New Zone Controls */}
          <div className="bg-slate-800 border border-slate-700 rounded-2xl p-4">
              <div className="flex justify-between items-center mb-4">
                <div>
                    <h4 className="text-white font-bold text-sm">Zone Protocols</h4>
                    <p className="text-xs text-slate-400">Execute mass signal overrides.</p>
                </div>
                <button onClick={() => setShowReportModal(true)} className="text-blue-400 hover:text-blue-300 text-xs flex items-center gap-1">
                    <FileText size={12}/> Generate Report
                </button>
              </div>
              <div className="flex gap-2">
                 {currentZoneMode !== 'NORMAL' ? (
                     <button 
                        onClick={() => onZoneAction('NORMAL')}
                        className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-green-600 hover:bg-green-500 rounded-lg text-xs text-white font-bold transition-colors animate-pulse"
                     >
                        <CheckCircle2 size={14} /> RESTORE NORMAL OPERATIONS
                     </button>
                 ) : (
                    <>
                        <button 
                            onClick={() => onZoneAction('VIP')}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-purple-900/30 border border-purple-500/30 hover:bg-purple-900/50 rounded-lg text-xs text-purple-200 transition-colors"
                        >
                            <Crown size={14} /> VIP Corridor
                        </button>
                        <button 
                            onClick={() => onZoneAction('LOCKDOWN')}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-red-900/30 border border-red-500/30 hover:bg-red-900/50 rounded-lg text-xs text-red-200 transition-colors"
                        >
                            <ShieldOff size={14} /> Lockdown
                        </button>
                    </>
                 )}
              </div>
          </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard 
            label="Total Vehicles" 
            value={stats.totalCars} 
            icon={Car} 
            color="blue" 
            subtext="+12% vs last hr"
        />
        <StatCard 
            label="Avg Congestion" 
            value={`${stats.averageCongestion}%`} 
            icon={Activity} 
            color={stats.averageCongestion > 70 ? 'red' : 'green'}
            subtext="Moderate Flow"
        />
        <StatCard 
            label="Active Alerts" 
            value={stats.activeAlerts} 
            icon={AlertOctagon} 
            color={stats.activeAlerts > 0 ? 'red' : 'blue'}
            subtext="Requires Attention"
        />
        <StatCard 
            label="System Health" 
            value={`${stats.systemHealth}%`} 
            icon={Cpu} 
            color="green"
            subtext="Optimal"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Chart */}
        <div className="lg:col-span-2 bg-slate-800 border border-slate-700 rounded-2xl p-6">
            <h3 className="text-lg font-bold text-white mb-4">Traffic Density Prediction (AI)</h3>
            <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={chartData}>
                        <defs>
                            <linearGradient id="colorCongestion" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3}/>
                                <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                            </linearGradient>
                            <linearGradient id="colorPred" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#a855f7" stopOpacity={0.3}/>
                                <stop offset="95%" stopColor="#a855f7" stopOpacity={0}/>
                            </linearGradient>
                        </defs>
                        <XAxis dataKey="time" stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} />
                        <YAxis stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${value}%`} />
                        <Tooltip 
                            contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f8fafc' }}
                            itemStyle={{ color: '#e2e8f0' }}
                        />
                        <Area type="monotone" dataKey="congestion" name="Actual Density" stroke="#3b82f6" fillOpacity={1} fill="url(#colorCongestion)" strokeWidth={2} />
                        <Area type="monotone" dataKey="prediction" name="AI Prediction" stroke="#a855f7" strokeDasharray="5 5" fillOpacity={1} fill="url(#colorPred)" strokeWidth={2} />
                    </AreaChart>
                </ResponsiveContainer>
            </div>
        </div>

        {/* AI Recommendations Panel */}
        <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 flex flex-col">
             <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                <Cpu className="w-5 h-5 text-purple-400" />
                AI Insights
             </h3>
             <div className="flex-1 space-y-4 overflow-y-auto pr-2">
                <div className="p-3 bg-slate-700/50 rounded-lg border border-slate-600">
                    <p className="text-sm text-slate-300">
                        <span className="text-purple-400 font-bold block mb-1">Signal Optimization</span>
                        Increased green light duration at "Connaught Place" by 15s due to incoming volume surge.
                    </p>
                </div>
                <div className="p-3 bg-slate-700/50 rounded-lg border border-slate-600">
                    <p className="text-sm text-slate-300">
                        <span className="text-yellow-400 font-bold block mb-1">Congestion Warning</span>
                        Predicted bottleneck at "Silk Board Junction" in 10 minutes. Rerouting suggestion enabled.
                    </p>
                </div>
                <div className="p-3 bg-slate-700/50 rounded-lg border border-slate-600">
                    <p className="text-sm text-slate-300">
                        <span className="text-blue-400 font-bold block mb-1">Efficiency</span>
                        Current adaptive algorithms improved flow by 18% compared to static timing.
                    </p>
                </div>
             </div>
        </div>
      </div>

      {/* Live Intersections Preview */}
      <div>
        <h3 className="text-lg font-bold text-white mb-4">Critical Intersections</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {intersections.slice(0, 3).map(intersection => (
                <IntersectionCard key={intersection.id} data={intersection} onEmergencyToggle={onEmergencyToggle} />
            ))}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;